Repository goormthon-Univ/TEAM_12_2, pull requests merged in 2023-11, with the labels that each got.

#1 [Feature] 인프라 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/letsRoll/letsRoll/Comment_Feeling/entity/Comment.java
  src/main/java/com/letsRoll/letsRoll/Comment_Feeling/entity/Feeling.java
  src/main/java/com/letsRoll/letsRoll/Goal/entity/Goal.java
  src/main/java/com/letsRoll/letsRoll/Goal/entity/GoalAgree.java
  src/main/java/com/letsRoll/letsRoll/LetsRollApplication.java
  src/main/java/com/letsRoll/letsRoll/Member/entity/Member.java
  src/main/java/com/letsRoll/letsRoll/Memoir/entity/Memoir.java
  src/main/java/com/letsRoll/letsRoll/Project/entity/Project.java
  src/main/java/com/letsRoll/letsRoll/Todo/entity/Todo.java
  src/main/java/com/letsRoll/letsRoll/Todo/entity/TodoEndManager.java
  src/main/java/com/letsRoll/letsRoll/Todo/entity/TodoManager.java
  src/main/java/com/letsRoll/letsRoll/User/entity/User.java
  src/main/java/com/letsRoll/letsRoll/global/common/BaseEntity.java
  src/main/java/com/letsRoll/letsRoll/global/common/BaseResponse.java
  src/main/java/com/letsRoll/letsRoll/global/enums/CommentType.java
  src/main/java/com/letsRoll/letsRoll/global/enums/Emoji.java
  src/main/java/com/letsRoll/letsRoll/global/enums/Mode.java
  src/main/java/com/letsRoll/letsRoll/global/exception/BaseException.java
  src/main/java/com/letsRoll/letsRoll/global/exception/BaseResponseCode.java
  src/main/java/com/letsRoll/letsRoll/global/exception/ExceptionHandlerAdvice.java
  src/main/resources/application.properties
  src/test/java/com/letsRoll/letsRoll/LetsRollApplicationTests.java
Labels: infra, feature

#8 [feature] projectDetail 한 프로젝트 내 프로젝트 정보, 멤버, 골, 골 동의 리스트 전체 조회
  src/main/java/com/letsRoll/letsRoll/Goal/controller/GoalController.java
  src/main/java/com/letsRoll/letsRoll/Goal/dto/GoalDto.java
  src/main/java/com/letsRoll/letsRoll/Goal/dto/res/GoalAgreeMemberCheckResDto.java
  src/main/java/com/letsRoll/letsRoll/Goal/entity/Goal.java
  src/main/java/com/letsRoll/letsRoll/Goal/entity/GoalAgree.java
  src/main/java/com/letsRoll/letsRoll/Goal/service/GoalService.java
  src/main/java/com/letsRoll/letsRoll/Member/entity/Member.java
  src/main/java/com/letsRoll/letsRoll/Project/controller/ProjectController.java
  src/main/java/com/letsRoll/letsRoll/Project/entity/Project.java
  src/main/java/com/letsRoll/letsRoll/Project/service/ProjectService.java
Labels: feature

#12 [fix]사용하지 않는 TodoResDto삭제, 전달하는 resdto 속성 이름 변경
  .gitignore
  src/main/java/com/letsRoll/letsRoll/Comment_Feeling/dto/CommentAssembler.java
  src/main/java/com/letsRoll/letsRoll/Comment_Feeling/dto/res/CommentInfoDto.java
  src/main/java/com/letsRoll/letsRoll/Comment_Feeling/dto/res/TodoCommentResDto.java
  src/main/java/com/letsRoll/letsRoll/Todo/controller/TodoController.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/TodoAssembler.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/res/MyTodoResDto.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/res/TodoListResDto.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/res/TodoResDto.java
Labels: fix

#13 [Feature] 월별 모든 todo를 완료한, 완료하지 않은 날짜 조회
  src/main/java/com/letsRoll/letsRoll/Todo/controller/TodoController.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/TodoAssembler.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/res/MonthlyCheckTodoListResDto.java
  src/main/java/com/letsRoll/letsRoll/Todo/repository/TodoRepository.java
  src/main/java/com/letsRoll/letsRoll/Todo/service/TodoService.java
Labels: feature

#15 [Feature]report goal project member
  src/main/java/com/letsRoll/letsRoll/Goal/controller/GoalController.java
  src/main/java/com/letsRoll/letsRoll/Goal/dto/res/ReportGoalResDto.java
  src/main/java/com/letsRoll/letsRoll/Goal/service/GoalAgreeService.java
  src/main/java/com/letsRoll/letsRoll/Goal/service/GoalService.java
  src/main/java/com/letsRoll/letsRoll/Member/controller/MemberController.java
  src/main/java/com/letsRoll/letsRoll/Member/repository/MemberRepository.java
  src/main/java/com/letsRoll/letsRoll/Member/service/MemberService.java
  src/main/java/com/letsRoll/letsRoll/Todo/controller/TodoController.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/TodoAssembler.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/res/AllReportTodo.java
  src/main/java/com/letsRoll/letsRoll/Todo/dto/res/ReportTodo.java
  src/main/java/com/letsRoll/letsRoll/Todo/repository/TodoEndManagerRepository.java
  src/main/java/com/letsRoll/letsRoll/Todo/service/TodoService.java
Labels: feature
